### ISSUE TITLE
TME GetPricesAndStocks rate limit is too conservative

### ISSUE THREAD

**Issue by ondras12345** [30350n/inventree_part_import#28]
https://github.com/30350n/inventree_part_import/commit/f8ea691d72f4775f961fb3cfaf4e3764a39a013b introduced a limit to 1 request every 2.5 seconds. However, the e-mail TME sent says:
> We're reducing the maximum API requests to **two per second** for actions:
> - /Products/GetStocks
> - /Products/GetDeliveryTime
> - /Products/GetPrices
> - /Products/GetPricesAndStocks

Thus, I believe a limit of just over 0.5 s should be sufficient.

**Comment by 30350n** [comment]
Duh! I completely missread that in the E-Mail they sent and literally missread it again just now. That really took a while to register ...

Will reduce the limit to 0.6s. Did it actually affect you though? I would've assumed everything else would probably take >2s anyways.

**Comment by ondras12345** [comment]
I did not actually test this, I noticed in git diff and thought you probably misread the e-mail.
Thanks for fixing it.

**Comment by 30350n** [comment]
Gotcha, yeah I totally did 😅
