### ISSUE TITLE
Crash when importing parts due to property validation failure

### ISSUE THREAD

**Issue by cmidgley** [30350n/inventree_part_import#36]
When importing properties for parts with a unit defined and the value from the supplier API does not pass Inventree validation, the program crashes due to an invalid dereference.

To reproduce the crash, import 'USBLC6-2SC6Y' from Digikey (using the [example configuration files](https://github.com/30350n/inventree_part_import_config)):

```
inventree_part_import -o digikey USBLC6-2SC6Y
```

The relevant part of the stack crawl is:

```
  File "...\inventree_part_import\part_importer.py", line 461, in update_parameter
    return f"failed to update parameter '{parameter.name}' to '{value}' with '{msg}'"
 ```
 
 This is because `parameter` does not have a 'name' property (it is an opaque object).

**Comment by 30350n** [comment]
Thanks for catching this and reporting!

You can disable `Enforce Parameter Units` btw (that's what I did, so I didn't have a chance to catch this myself ^^).
![image](https://github.com/30350n/inventree_part_import/assets/34186858/8a3d153c-7718-469f-8044-6cf9816a7530)

**Comment by cmidgley** [comment]
That's a much better solution.  Merged and confirmed fixed.
