### ISSUE TITLE
LCSC not working

### ISSUE THREAD

**Issue by Zontex** [30350n/inventree_part_import#56]
Trying as follows inventree-part-import C181133
gives me:

successfully setup categories!

searching for C181133 ...
warning: failed to get page, retrying in 3.0s with new session and user agent
(no results at LCSC)

reimporting failed/incomplete parts in interactive mode ...

searching for C181133 ...
(no results at LCSC)

the following parts failed to import:
C181133

Tried also with ID, names and other things.

**Comment by 30350n** [comment]
This was fixed in #48. If you [install the newest version from master](https://github.com/30350n/inventree_part_import/issues/49#issuecomment-2182638674) it will work.

**Comment by Zontex** [comment]
Pip is outdated.
fixed it by : pip install git+https://github.com/30350n/inventree_part_import.git

**Comment by 30350n** [comment]
Yep, exactly. I haven't yet made a new release because mouser is still partially broken.
