### ISSUE TITLE
Initial Setup Broken

### ISSUE THREAD

**Issue by TimGoll** [30350n/inventree_part_import#59]
I'm using the current release in pipx, which I think is `1.7`, I'm not sure how I get the exact version.

The problem is that the initial setup only generates the following folders/files:
![image](https://github.com/user-attachments/assets/655f1754-80e1-42f6-8b1b-bfbe05a5c7ab)

In the same folders - I think - `inventree.yaml`, `config.yaml` and `suppliers.yaml` should be created. But this doesn't happen. When starting the tool for the first time, this is the output:
![image](https://github.com/user-attachments/assets/e2c028f1-d9d8-46e5-88c4-a7eccb621c6b)

My guess is that the issue lies here:
https://github.com/30350n/inventree_part_import/blob/c044691bc03b3761d026e236f7dad252a531104a/inventree_part_import/config/__init__.py#L297-L298

**Comment by TimGoll** [comment]
> > I'm using the current release in pipx, which I think is 1.7, I'm not sure how I get the exact version.
> 
> `inventree-part-import --version` should do the trick.

![image](https://github.com/user-attachments/assets/6e3e28d2-4541-4f7b-9094-082c07c09cd2)

I don't think that parameter exists

**Comment by TimGoll** [comment]
> This is expected behavior, config initialization happens when you first import a part. Calling `inventree-part-import` without any arguments won't trigger it.

Oh, then I misunderstood the readme. I thought the initial setup takes place before you import your first part.

**Comment by 30350n** [comment]
You are running a version <= 1.5 in that case. Try upgrading via `pipx upgrade inventree-part-import`.

**Comment by 30350n** [comment]
> Oh, then I misunderstood the readme. I thought the initial setup takes place before you import your first part.

Not really. It does take place before importing your first part, but you have to "try" to import a part to trigger it ^^

**Comment by TimGoll** [comment]
> pipx upgrade inventree-part-import

But I just installed it today? Nevertheless, I tried it, this is the output:

![image](https://github.com/user-attachments/assets/44707a4d-bb2c-4b0b-9a14-386ff1c21e23)

**Comment by 30350n** [comment]
That's odd. And you only installed it via pipx?
Can you confirm that it's not available anymore if you `pipx uninstall` it? (And that it still doesn't default to 1.7 if you reinstall it again afterwards?)

**Comment by TimGoll** [comment]
> That's odd. And you only installed it via pipx? Can you confirm that it's not available anymore if you `pipx uninstall` it? (And that it still doesn't default to 1.7 if you reinstall it again afterwards?)

I tried that before reporting that issue, but I will try it again

**Comment by 30350n** [comment]
Yeah then you might have installed it via normal pip or something? Check what `which inventree-part-import` outputs.

**Comment by TimGoll** [comment]
> Yeah then you might have installed it via normal pip or something? Check what `which inventree-part-import` outputs.

![image](https://github.com/user-attachments/assets/1a18fff2-65a5-4279-ad99-75be0192c5e0)

Strange. but I tried it already in February of this year, but I'm absolutely sure that I used pipx at that point as well, this is why I used pipx uninstall today before reporting the issue. I have no idea where the pip package came from. But it seems to be resolved

**Comment by TimGoll** [comment]
Thanks alot for your help! Really appreciated

**Comment by 30350n** [comment]
No problem ^^

**Comment by TimGoll** [comment]
Okay, I'm stuck again. I tried to access my inventree server via my local machine over this tool and failed. I assumed it was because of our company's proxies.

![image](https://github.com/user-attachments/assets/3cf41dc9-1343-46ca-bb60-f2897d8c6af7)

However, I tried the same thing with SSH access on the server as well and it failed again. Although with a different error this time:

![image](https://github.com/user-attachments/assets/aa392bf4-d330-4a0f-a5d8-5c19bab51a17)

I'm pretty sure I was able to log in February without any issues with the host+token. I'm confused why I need the user and password anyway. Also the documentation seems to suggest otherwise as well. I'm a bit lost.

**Comment by 30350n** [comment]
From the [README](https://github.com/30350n/inventree_part_import?tab=readme-ov-file#inventreeyaml):
> token: the user token to authenticate with (this will be retrieved automatically by the CLI)

You have to authenticate with your password once, then the token gets retrived from the server and stored in the `inventree.yaml`.

So if you think the problem lies with password auth, you can try providing the `host` and `token` in the `inventree.yaml` directly.

**Comment by TimGoll** [comment]
Ahh, okay, I didn't get that. Personally I'd have preferred it to just enter the auth code. Thanks again!

**Comment by TimGoll** [comment]
I am unable to make it work, I don't know why. I entered the URL and token manually into the file. This way it now actually tries to connect, but the authentication fails. Not sure why though, because it is the same token I use in KiCad.

![image](https://github.com/user-attachments/assets/490135ff-5f31-43b0-9103-4ece23a02d39)

Any ideas?

**Comment by TimGoll** [comment]
Maybe as a feedback: The issue lies in inventree. We had two problems. The aforementioned Certs, but also the wrong url (I used the kicad api endpoint). Inventree did not check the output and silently failed at this point: 
https://github.com/inventree/inventree-python/blob/80ff58de0757cc6ce37a83bab0a1355819745746/inventree/api.py#L212

This happens because the return text is no json, but the login page HTML.

Maybe your tool should use the inventree logger and print it as well when enabling `verbose`. This would have helped us when debugging.

**Comment by 30350n** [comment]
> Maybe your tool should use the inventree logger and print it as well when enabling `verbose`. This would have helped us when debugging.

Good point! I was actually briefly thinking about that yesterday and wondering why it didn't do that already. It's implemented in [`bc09996`](https://github.com/30350n/inventree_part_import/commit/bc09996e96f7c9e5fbc50dd8c3ff50177f60001d) now.

**Comment by TimGoll** [comment]
awesome, keep up with that good work!
