### ISSUE TITLE
CSV not a supported file format

### ISSUE THREAD

**Issue by si-hb** [30350n/inventree_part_import#6]
```
$ inventree-part-import parts.csv
reading parts.csv ...
error: .csv is not a supported file format
```

**Comment by 30350n** [comment]
Hows the csv formatted? Can you share it?

**Comment by 30350n** [comment]
Seems like [`tablib`](https://github.com/jazzband/tablib) doesn't handle single column files. Added some code to handle this case manually now, should be fixed!
