### ISSUE TITLE
Documented command name utilizes underscores, however only dashes work for me

### ISSUE THREAD

**Issue by si-hb** [30350n/inventree_part_import#7]
Use of  `inventree_part_import`  as documented:

![image](https://github.com/30350n/inventree_part_import/assets/1800110/315f2efb-ef75-4820-8f48-ab7f326e18dc)

```
$ inventree_part_import
inventree_part_import: command not found
```

`inventree-part-import` works however

**Comment by 30350n** [comment]
Thanks, fixed.
