### ISSUE TITLE
initial setup / config does not run?

### ISSUE THREAD

**Issue by dubajj** [30350n/inventree_part_import#8]
repro steps:
1) `pipx install inventree-part-import`
2) `inventree-part-import` just shows the help
3) `inventree-part-import -i default` just shows the help
4) `inventree-part-import --configure mouser` errors out that there is no configuration setup 
```
 FileNotFoundError: [Errno 2] No such file or directory: '/home/jasper/.config/inventree_part_import/suppliers.yaml'
```

OS: PopOS 22.04

Is there a way to force the configuration to run?

**Comment by 30350n** [comment]
Yeah, you have to actually import a part: `inventree-part-import TL074HIDR` for example

**Comment by 30350n** [comment]
I will look into fixing 4. though.

**Comment by 30350n** [comment]
4. is fixed now.
